# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/coins/DirhamCliV2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/coins/DirhamCliV2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/coins/DirhamCliV2/CMakeFiles /root/coins/DirhamCliV2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/coins/DirhamCliV2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named walletd

# Build rule for target.
walletd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 walletd
.PHONY : walletd

# fast build rule for target.
walletd/fast:
	$(MAKE) -f CMakeFiles/walletd.dir/build.make CMakeFiles/walletd.dir/build
.PHONY : walletd/fast

#=============================================================================
# Target rules for targets named cryptonoted

# Build rule for target.
cryptonoted: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonoted
.PHONY : cryptonoted

# fast build rule for target.
cryptonoted/fast:
	$(MAKE) -f CMakeFiles/cryptonoted.dir/build.make CMakeFiles/cryptonoted.dir/build
.PHONY : cryptonoted/fast

#=============================================================================
# Target rules for targets named cryptonote-core

# Build rule for target.
cryptonote-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote-core
.PHONY : cryptonote-core

# fast build rule for target.
cryptonote-core/fast:
	$(MAKE) -f CMakeFiles/cryptonote-core.dir/build.make CMakeFiles/cryptonote-core.dir/build
.PHONY : cryptonote-core/fast

#=============================================================================
# Target rules for targets named cryptonote-crypto

# Build rule for target.
cryptonote-crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptonote-crypto
.PHONY : cryptonote-crypto

# fast build rule for target.
cryptonote-crypto/fast:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/build
.PHONY : cryptonote-crypto/fast

src/crypto/blake256.o: src/crypto/blake256.c.o

.PHONY : src/crypto/blake256.o

# target to build an object file
src/crypto/blake256.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/blake256.c.o
.PHONY : src/crypto/blake256.c.o

src/crypto/blake256.i: src/crypto/blake256.c.i

.PHONY : src/crypto/blake256.i

# target to preprocess a source file
src/crypto/blake256.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/blake256.c.i
.PHONY : src/crypto/blake256.c.i

src/crypto/blake256.s: src/crypto/blake256.c.s

.PHONY : src/crypto/blake256.s

# target to generate assembly for a file
src/crypto/blake256.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/blake256.c.s
.PHONY : src/crypto/blake256.c.s

src/crypto/chacha.o: src/crypto/chacha.c.o

.PHONY : src/crypto/chacha.o

# target to build an object file
src/crypto/chacha.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/chacha.c.o
.PHONY : src/crypto/chacha.c.o

src/crypto/chacha.i: src/crypto/chacha.c.i

.PHONY : src/crypto/chacha.i

# target to preprocess a source file
src/crypto/chacha.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/chacha.c.i
.PHONY : src/crypto/chacha.c.i

src/crypto/chacha.s: src/crypto/chacha.c.s

.PHONY : src/crypto/chacha.s

# target to generate assembly for a file
src/crypto/chacha.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/chacha.c.s
.PHONY : src/crypto/chacha.c.s

src/crypto/crypto-ops-data.o: src/crypto/crypto-ops-data.c.o

.PHONY : src/crypto/crypto-ops-data.o

# target to build an object file
src/crypto/crypto-ops-data.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops-data.c.o
.PHONY : src/crypto/crypto-ops-data.c.o

src/crypto/crypto-ops-data.i: src/crypto/crypto-ops-data.c.i

.PHONY : src/crypto/crypto-ops-data.i

# target to preprocess a source file
src/crypto/crypto-ops-data.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops-data.c.i
.PHONY : src/crypto/crypto-ops-data.c.i

src/crypto/crypto-ops-data.s: src/crypto/crypto-ops-data.c.s

.PHONY : src/crypto/crypto-ops-data.s

# target to generate assembly for a file
src/crypto/crypto-ops-data.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops-data.c.s
.PHONY : src/crypto/crypto-ops-data.c.s

src/crypto/crypto-ops.o: src/crypto/crypto-ops.c.o

.PHONY : src/crypto/crypto-ops.o

# target to build an object file
src/crypto/crypto-ops.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops.c.o
.PHONY : src/crypto/crypto-ops.c.o

src/crypto/crypto-ops.i: src/crypto/crypto-ops.c.i

.PHONY : src/crypto/crypto-ops.i

# target to preprocess a source file
src/crypto/crypto-ops.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops.c.i
.PHONY : src/crypto/crypto-ops.c.i

src/crypto/crypto-ops.s: src/crypto/crypto-ops.c.s

.PHONY : src/crypto/crypto-ops.s

# target to generate assembly for a file
src/crypto/crypto-ops.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto-ops.c.s
.PHONY : src/crypto/crypto-ops.c.s

src/crypto/crypto.o: src/crypto/crypto.cpp.o

.PHONY : src/crypto/crypto.o

# target to build an object file
src/crypto/crypto.cpp.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto.cpp.o
.PHONY : src/crypto/crypto.cpp.o

src/crypto/crypto.i: src/crypto/crypto.cpp.i

.PHONY : src/crypto/crypto.i

# target to preprocess a source file
src/crypto/crypto.cpp.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto.cpp.i
.PHONY : src/crypto/crypto.cpp.i

src/crypto/crypto.s: src/crypto/crypto.cpp.s

.PHONY : src/crypto/crypto.s

# target to generate assembly for a file
src/crypto/crypto.cpp.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/crypto.cpp.s
.PHONY : src/crypto/crypto.cpp.s

src/crypto/groestl.o: src/crypto/groestl.c.o

.PHONY : src/crypto/groestl.o

# target to build an object file
src/crypto/groestl.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/groestl.c.o
.PHONY : src/crypto/groestl.c.o

src/crypto/groestl.i: src/crypto/groestl.c.i

.PHONY : src/crypto/groestl.i

# target to preprocess a source file
src/crypto/groestl.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/groestl.c.i
.PHONY : src/crypto/groestl.c.i

src/crypto/groestl.s: src/crypto/groestl.c.s

.PHONY : src/crypto/groestl.s

# target to generate assembly for a file
src/crypto/groestl.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/groestl.c.s
.PHONY : src/crypto/groestl.c.s

src/crypto/hash-extra-blake.o: src/crypto/hash-extra-blake.c.o

.PHONY : src/crypto/hash-extra-blake.o

# target to build an object file
src/crypto/hash-extra-blake.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-blake.c.o
.PHONY : src/crypto/hash-extra-blake.c.o

src/crypto/hash-extra-blake.i: src/crypto/hash-extra-blake.c.i

.PHONY : src/crypto/hash-extra-blake.i

# target to preprocess a source file
src/crypto/hash-extra-blake.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-blake.c.i
.PHONY : src/crypto/hash-extra-blake.c.i

src/crypto/hash-extra-blake.s: src/crypto/hash-extra-blake.c.s

.PHONY : src/crypto/hash-extra-blake.s

# target to generate assembly for a file
src/crypto/hash-extra-blake.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-blake.c.s
.PHONY : src/crypto/hash-extra-blake.c.s

src/crypto/hash-extra-groestl.o: src/crypto/hash-extra-groestl.c.o

.PHONY : src/crypto/hash-extra-groestl.o

# target to build an object file
src/crypto/hash-extra-groestl.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-groestl.c.o
.PHONY : src/crypto/hash-extra-groestl.c.o

src/crypto/hash-extra-groestl.i: src/crypto/hash-extra-groestl.c.i

.PHONY : src/crypto/hash-extra-groestl.i

# target to preprocess a source file
src/crypto/hash-extra-groestl.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-groestl.c.i
.PHONY : src/crypto/hash-extra-groestl.c.i

src/crypto/hash-extra-groestl.s: src/crypto/hash-extra-groestl.c.s

.PHONY : src/crypto/hash-extra-groestl.s

# target to generate assembly for a file
src/crypto/hash-extra-groestl.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-groestl.c.s
.PHONY : src/crypto/hash-extra-groestl.c.s

src/crypto/hash-extra-jh.o: src/crypto/hash-extra-jh.c.o

.PHONY : src/crypto/hash-extra-jh.o

# target to build an object file
src/crypto/hash-extra-jh.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-jh.c.o
.PHONY : src/crypto/hash-extra-jh.c.o

src/crypto/hash-extra-jh.i: src/crypto/hash-extra-jh.c.i

.PHONY : src/crypto/hash-extra-jh.i

# target to preprocess a source file
src/crypto/hash-extra-jh.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-jh.c.i
.PHONY : src/crypto/hash-extra-jh.c.i

src/crypto/hash-extra-jh.s: src/crypto/hash-extra-jh.c.s

.PHONY : src/crypto/hash-extra-jh.s

# target to generate assembly for a file
src/crypto/hash-extra-jh.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-jh.c.s
.PHONY : src/crypto/hash-extra-jh.c.s

src/crypto/hash-extra-skein.o: src/crypto/hash-extra-skein.c.o

.PHONY : src/crypto/hash-extra-skein.o

# target to build an object file
src/crypto/hash-extra-skein.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-skein.c.o
.PHONY : src/crypto/hash-extra-skein.c.o

src/crypto/hash-extra-skein.i: src/crypto/hash-extra-skein.c.i

.PHONY : src/crypto/hash-extra-skein.i

# target to preprocess a source file
src/crypto/hash-extra-skein.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-skein.c.i
.PHONY : src/crypto/hash-extra-skein.c.i

src/crypto/hash-extra-skein.s: src/crypto/hash-extra-skein.c.s

.PHONY : src/crypto/hash-extra-skein.s

# target to generate assembly for a file
src/crypto/hash-extra-skein.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash-extra-skein.c.s
.PHONY : src/crypto/hash-extra-skein.c.s

src/crypto/hash.o: src/crypto/hash.c.o

.PHONY : src/crypto/hash.o

# target to build an object file
src/crypto/hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash.c.o
.PHONY : src/crypto/hash.c.o

src/crypto/hash.i: src/crypto/hash.c.i

.PHONY : src/crypto/hash.i

# target to preprocess a source file
src/crypto/hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash.c.i
.PHONY : src/crypto/hash.c.i

src/crypto/hash.s: src/crypto/hash.c.s

.PHONY : src/crypto/hash.s

# target to generate assembly for a file
src/crypto/hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/hash.c.s
.PHONY : src/crypto/hash.c.s

src/crypto/jh.o: src/crypto/jh.c.o

.PHONY : src/crypto/jh.o

# target to build an object file
src/crypto/jh.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/jh.c.o
.PHONY : src/crypto/jh.c.o

src/crypto/jh.i: src/crypto/jh.c.i

.PHONY : src/crypto/jh.i

# target to preprocess a source file
src/crypto/jh.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/jh.c.i
.PHONY : src/crypto/jh.c.i

src/crypto/jh.s: src/crypto/jh.c.s

.PHONY : src/crypto/jh.s

# target to generate assembly for a file
src/crypto/jh.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/jh.c.s
.PHONY : src/crypto/jh.c.s

src/crypto/keccak.o: src/crypto/keccak.c.o

.PHONY : src/crypto/keccak.o

# target to build an object file
src/crypto/keccak.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/keccak.c.o
.PHONY : src/crypto/keccak.c.o

src/crypto/keccak.i: src/crypto/keccak.c.i

.PHONY : src/crypto/keccak.i

# target to preprocess a source file
src/crypto/keccak.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/keccak.c.i
.PHONY : src/crypto/keccak.c.i

src/crypto/keccak.s: src/crypto/keccak.c.s

.PHONY : src/crypto/keccak.s

# target to generate assembly for a file
src/crypto/keccak.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/keccak.c.s
.PHONY : src/crypto/keccak.c.s

src/crypto/oaes_lib.o: src/crypto/oaes_lib.c.o

.PHONY : src/crypto/oaes_lib.o

# target to build an object file
src/crypto/oaes_lib.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/oaes_lib.c.o
.PHONY : src/crypto/oaes_lib.c.o

src/crypto/oaes_lib.i: src/crypto/oaes_lib.c.i

.PHONY : src/crypto/oaes_lib.i

# target to preprocess a source file
src/crypto/oaes_lib.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/oaes_lib.c.i
.PHONY : src/crypto/oaes_lib.c.i

src/crypto/oaes_lib.s: src/crypto/oaes_lib.c.s

.PHONY : src/crypto/oaes_lib.s

# target to generate assembly for a file
src/crypto/oaes_lib.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/oaes_lib.c.s
.PHONY : src/crypto/oaes_lib.c.s

src/crypto/random.o: src/crypto/random.c.o

.PHONY : src/crypto/random.o

# target to build an object file
src/crypto/random.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/random.c.o
.PHONY : src/crypto/random.c.o

src/crypto/random.i: src/crypto/random.c.i

.PHONY : src/crypto/random.i

# target to preprocess a source file
src/crypto/random.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/random.c.i
.PHONY : src/crypto/random.c.i

src/crypto/random.s: src/crypto/random.c.s

.PHONY : src/crypto/random.s

# target to generate assembly for a file
src/crypto/random.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/random.c.s
.PHONY : src/crypto/random.c.s

src/crypto/skein.o: src/crypto/skein.c.o

.PHONY : src/crypto/skein.o

# target to build an object file
src/crypto/skein.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/skein.c.o
.PHONY : src/crypto/skein.c.o

src/crypto/skein.i: src/crypto/skein.c.i

.PHONY : src/crypto/skein.i

# target to preprocess a source file
src/crypto/skein.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/skein.c.i
.PHONY : src/crypto/skein.c.i

src/crypto/skein.s: src/crypto/skein.c.s

.PHONY : src/crypto/skein.s

# target to generate assembly for a file
src/crypto/skein.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/skein.c.s
.PHONY : src/crypto/skein.c.s

src/crypto/slow-hash.o: src/crypto/slow-hash.c.o

.PHONY : src/crypto/slow-hash.o

# target to build an object file
src/crypto/slow-hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.c.o
.PHONY : src/crypto/slow-hash.c.o

src/crypto/slow-hash.i: src/crypto/slow-hash.c.i

.PHONY : src/crypto/slow-hash.i

# target to preprocess a source file
src/crypto/slow-hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.c.i
.PHONY : src/crypto/slow-hash.c.i

src/crypto/slow-hash.s: src/crypto/slow-hash.c.s

.PHONY : src/crypto/slow-hash.s

# target to generate assembly for a file
src/crypto/slow-hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.c.s
.PHONY : src/crypto/slow-hash.c.s

src/crypto/slow-hash.o: src/crypto/slow-hash.cpp.o

.PHONY : src/crypto/slow-hash.o

# target to build an object file
src/crypto/slow-hash.cpp.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.cpp.o
.PHONY : src/crypto/slow-hash.cpp.o

src/crypto/slow-hash.i: src/crypto/slow-hash.cpp.i

.PHONY : src/crypto/slow-hash.i

# target to preprocess a source file
src/crypto/slow-hash.cpp.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.cpp.i
.PHONY : src/crypto/slow-hash.cpp.i

src/crypto/slow-hash.s: src/crypto/slow-hash.cpp.s

.PHONY : src/crypto/slow-hash.s

# target to generate assembly for a file
src/crypto/slow-hash.cpp.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/slow-hash.cpp.s
.PHONY : src/crypto/slow-hash.cpp.s

src/crypto/tree-hash.o: src/crypto/tree-hash.c.o

.PHONY : src/crypto/tree-hash.o

# target to build an object file
src/crypto/tree-hash.c.o:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/tree-hash.c.o
.PHONY : src/crypto/tree-hash.c.o

src/crypto/tree-hash.i: src/crypto/tree-hash.c.i

.PHONY : src/crypto/tree-hash.i

# target to preprocess a source file
src/crypto/tree-hash.c.i:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/tree-hash.c.i
.PHONY : src/crypto/tree-hash.c.i

src/crypto/tree-hash.s: src/crypto/tree-hash.c.s

.PHONY : src/crypto/tree-hash.s

# target to generate assembly for a file
src/crypto/tree-hash.c.s:
	$(MAKE) -f CMakeFiles/cryptonote-crypto.dir/build.make CMakeFiles/cryptonote-crypto.dir/src/crypto/tree-hash.c.s
.PHONY : src/crypto/tree-hash.c.s

src/main_tests.o: src/main_tests.cpp.o

.PHONY : src/main_tests.o

# target to build an object file
src/main_tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main_tests.cpp.o
.PHONY : src/main_tests.cpp.o

src/main_tests.i: src/main_tests.cpp.i

.PHONY : src/main_tests.i

# target to preprocess a source file
src/main_tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main_tests.cpp.i
.PHONY : src/main_tests.cpp.i

src/main_tests.s: src/main_tests.cpp.s

.PHONY : src/main_tests.s

# target to generate assembly for a file
src/main_tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main_tests.cpp.s
.PHONY : src/main_tests.cpp.s

src/main_walletd.o: src/main_walletd.cpp.o

.PHONY : src/main_walletd.o

# target to build an object file
src/main_walletd.cpp.o:
	$(MAKE) -f CMakeFiles/walletd.dir/build.make CMakeFiles/walletd.dir/src/main_walletd.cpp.o
.PHONY : src/main_walletd.cpp.o

src/main_walletd.i: src/main_walletd.cpp.i

.PHONY : src/main_walletd.i

# target to preprocess a source file
src/main_walletd.cpp.i:
	$(MAKE) -f CMakeFiles/walletd.dir/build.make CMakeFiles/walletd.dir/src/main_walletd.cpp.i
.PHONY : src/main_walletd.cpp.i

src/main_walletd.s: src/main_walletd.cpp.s

.PHONY : src/main_walletd.s

# target to generate assembly for a file
src/main_walletd.cpp.s:
	$(MAKE) -f CMakeFiles/walletd.dir/build.make CMakeFiles/walletd.dir/src/main_walletd.cpp.s
.PHONY : src/main_walletd.cpp.s

tests/crypto/test_crypto.o: tests/crypto/test_crypto.cpp.o

.PHONY : tests/crypto/test_crypto.o

# target to build an object file
tests/crypto/test_crypto.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/crypto/test_crypto.cpp.o
.PHONY : tests/crypto/test_crypto.cpp.o

tests/crypto/test_crypto.i: tests/crypto/test_crypto.cpp.i

.PHONY : tests/crypto/test_crypto.i

# target to preprocess a source file
tests/crypto/test_crypto.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/crypto/test_crypto.cpp.i
.PHONY : tests/crypto/test_crypto.cpp.i

tests/crypto/test_crypto.s: tests/crypto/test_crypto.cpp.s

.PHONY : tests/crypto/test_crypto.s

# target to generate assembly for a file
tests/crypto/test_crypto.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/crypto/test_crypto.cpp.s
.PHONY : tests/crypto/test_crypto.cpp.s

tests/hash/test_hash.o: tests/hash/test_hash.cpp.o

.PHONY : tests/hash/test_hash.o

# target to build an object file
tests/hash/test_hash.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/hash/test_hash.cpp.o
.PHONY : tests/hash/test_hash.cpp.o

tests/hash/test_hash.i: tests/hash/test_hash.cpp.i

.PHONY : tests/hash/test_hash.i

# target to preprocess a source file
tests/hash/test_hash.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/hash/test_hash.cpp.i
.PHONY : tests/hash/test_hash.cpp.i

tests/hash/test_hash.s: tests/hash/test_hash.cpp.s

.PHONY : tests/hash/test_hash.s

# target to generate assembly for a file
tests/hash/test_hash.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/hash/test_hash.cpp.s
.PHONY : tests/hash/test_hash.cpp.s

tests/json/test_json.o: tests/json/test_json.cpp.o

.PHONY : tests/json/test_json.o

# target to build an object file
tests/json/test_json.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/json/test_json.cpp.o
.PHONY : tests/json/test_json.cpp.o

tests/json/test_json.i: tests/json/test_json.cpp.i

.PHONY : tests/json/test_json.i

# target to preprocess a source file
tests/json/test_json.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/json/test_json.cpp.i
.PHONY : tests/json/test_json.cpp.i

tests/json/test_json.s: tests/json/test_json.cpp.s

.PHONY : tests/json/test_json.s

# target to generate assembly for a file
tests/json/test_json.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/json/test_json.cpp.s
.PHONY : tests/json/test_json.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tests"
	@echo "... walletd"
	@echo "... cryptonoted"
	@echo "... cryptonote-core"
	@echo "... cryptonote-crypto"
	@echo "... src/crypto/blake256.o"
	@echo "... src/crypto/blake256.i"
	@echo "... src/crypto/blake256.s"
	@echo "... src/crypto/chacha.o"
	@echo "... src/crypto/chacha.i"
	@echo "... src/crypto/chacha.s"
	@echo "... src/crypto/crypto-ops-data.o"
	@echo "... src/crypto/crypto-ops-data.i"
	@echo "... src/crypto/crypto-ops-data.s"
	@echo "... src/crypto/crypto-ops.o"
	@echo "... src/crypto/crypto-ops.i"
	@echo "... src/crypto/crypto-ops.s"
	@echo "... src/crypto/crypto.o"
	@echo "... src/crypto/crypto.i"
	@echo "... src/crypto/crypto.s"
	@echo "... src/crypto/groestl.o"
	@echo "... src/crypto/groestl.i"
	@echo "... src/crypto/groestl.s"
	@echo "... src/crypto/hash-extra-blake.o"
	@echo "... src/crypto/hash-extra-blake.i"
	@echo "... src/crypto/hash-extra-blake.s"
	@echo "... src/crypto/hash-extra-groestl.o"
	@echo "... src/crypto/hash-extra-groestl.i"
	@echo "... src/crypto/hash-extra-groestl.s"
	@echo "... src/crypto/hash-extra-jh.o"
	@echo "... src/crypto/hash-extra-jh.i"
	@echo "... src/crypto/hash-extra-jh.s"
	@echo "... src/crypto/hash-extra-skein.o"
	@echo "... src/crypto/hash-extra-skein.i"
	@echo "... src/crypto/hash-extra-skein.s"
	@echo "... src/crypto/hash.o"
	@echo "... src/crypto/hash.i"
	@echo "... src/crypto/hash.s"
	@echo "... src/crypto/jh.o"
	@echo "... src/crypto/jh.i"
	@echo "... src/crypto/jh.s"
	@echo "... src/crypto/keccak.o"
	@echo "... src/crypto/keccak.i"
	@echo "... src/crypto/keccak.s"
	@echo "... src/crypto/oaes_lib.o"
	@echo "... src/crypto/oaes_lib.i"
	@echo "... src/crypto/oaes_lib.s"
	@echo "... src/crypto/random.o"
	@echo "... src/crypto/random.i"
	@echo "... src/crypto/random.s"
	@echo "... src/crypto/skein.o"
	@echo "... src/crypto/skein.i"
	@echo "... src/crypto/skein.s"
	@echo "... src/crypto/slow-hash.o"
	@echo "... src/crypto/slow-hash.i"
	@echo "... src/crypto/slow-hash.s"
	@echo "... src/crypto/slow-hash.o"
	@echo "... src/crypto/slow-hash.i"
	@echo "... src/crypto/slow-hash.s"
	@echo "... src/crypto/tree-hash.o"
	@echo "... src/crypto/tree-hash.i"
	@echo "... src/crypto/tree-hash.s"
	@echo "... src/main_tests.o"
	@echo "... src/main_tests.i"
	@echo "... src/main_tests.s"
	@echo "... src/main_walletd.o"
	@echo "... src/main_walletd.i"
	@echo "... src/main_walletd.s"
	@echo "... tests/crypto/test_crypto.o"
	@echo "... tests/crypto/test_crypto.i"
	@echo "... tests/crypto/test_crypto.s"
	@echo "... tests/hash/test_hash.o"
	@echo "... tests/hash/test_hash.i"
	@echo "... tests/hash/test_hash.s"
	@echo "... tests/json/test_json.o"
	@echo "... tests/json/test_json.i"
	@echo "... tests/json/test_json.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

